version: '3.8'
services:
  app:
    image: eid88805/lab8-app:latest
    ports:
      - "3000:3000"
    environment:
      # Passing the connection string using the DB service name ('mongo') as the hostname
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongo-data: